<a href="https://colab.research.google.com/github/karlmutch/udemy/blob/master/numpy_deep_learning_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear scratch

$${x}_1+x_2=2200$$
$$1.5x_1+4x_2=5050$$




In [0]:
import numpy as np
import numpy.linalg
import random

from datetime import datetime

In [0]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [0]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [4]:
5 * np.ones((2,3))

array([[5., 5., 5.],
       [5., 5., 5.]])

In [8]:
np.random.random((2,3))

array([[0.72309909, 0.03350804, 0.07798836],
       [0.5773543 , 0.94885968, 0.84039888]])

In [9]:
np.random.randn(2,3)

array([[0.6483395 , 0.89229093, 1.18288003],
       [0.4584108 , 1.42801453, 0.23886793]])

Do a speed test for matrix multiplications using lists, and using numpy

In [105]:
width, height = 18**2, 12**2
py_matrix_1 = [[random.randint(1,9) for x in range(width)] for y in range(height)]
py_matrix_2 = [[random.randint(1,9) for x in range(height)] for y in range(width)]
#py_matrix_1 = [[12, 7, 3], 
#    [4, 5, 6], 
#    [7, 8, 9]] 
  
# take a 3x4 matrix     
#py_matrix_2 = [[5, 8, 1, 2], 
#    [6, 7, 3, 0], 
#    [4, 5, 9, 1]] 
      
#py_matrix_1 = [[1,2,3], [4,5,6]]
#py_matrix_2 = [[7,8], [9,10], [11,12]]

result = [[0 for x in range(len(py_matrix_2[0]))] for y in range(len(py_matrix_1))]

start_time = datetime.now()
# by row of first array
for i in range(len(py_matrix_1)):
  # by column of second array
  for j in range(len(py_matrix_2[0])):
    # by row of second array in the single column
    for k in range(len(py_matrix_2)):
      result[i][j] += py_matrix_1[i][k] * py_matrix_2[k][j]

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

py_matrix_1=numpy.array([numpy.array(xi) for xi in py_matrix_1])
py_matrix_2=numpy.array([numpy.array(xi) for xi in py_matrix_2])

start_time = datetime.now()

py_matrix_1.dot(py_matrix_2)
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))


Duration: 0:00:02.030448
Duration: 0:00:00.008791
